name: sliding_box
description: A Flutter package create a widget that will display only one widget based on the current focused index and each change will be accompanied by an animation.
version: 0.0.2
homepage: https://github.com/farhanfadila1717/sliding_box
maintener: Farhan Fadila (@farhanfadila1717)

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
